первая попытка
OlgaSergeenko/java-filmorate pull request #1
Opened 2022-08-07 13:58 UTC by OlgaSergeenko

2022-08-08 10:09 UTC, OlgaSergeenko commented
Этот гит  - какой-то темный лес. Надеюсь, отправится нужная версия.
Прошу прощения за этот странный коммент

2022-08-09 09:13 UTC, Frilock requested changes
Добрый день, написал ряд комментариев к работе. Основное конечно, это разберитесь с gitIgnote =)

2022-08-09 09:13 UTC, Frilock commented on .gitignore
> -target/
Зачем вы все отсюда убрали? Папки targer, out и т.д. точно должны быть в gitIgnore. Иначе мне сейчас показывается 107 файлов, а должно быть порядка 15 =)

2022-08-09 09:13 UTC, Frilock commented on pom.xml
> +			<version>1.18.20</version>
Версии библиотек, которые вы подключаете в pom файле, принято указывать в properties, по аналогии с версией Java, а в поле version самой библиотеки указывать так ${simple-lib.version}. Это нужно для того, чтобы версии библиотек находились в одном месте и их изменении проходило безболезненно.

2022-08-09 09:13 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!films.containsKey(film.getId())) {
Вообще бы по хорошему этот кусок тоже в валидационный метод перенести

2022-08-09 09:13 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        }
форматирование сьехало

2022-08-09 09:13 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Вообще у данных контроллеров очень много общего, как задачка со звездочкой, можете сделать абстрактный контроллер и общую часть вынести туда.
Это на ваше усмотрение

2022-08-09 09:13 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(String name, String description, LocalDate releaseDate, int duration) {
Можете воспользоваться аннотацией RequaredArgsContructor, чтобы отказаться от этого

2022-08-09 09:13 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotNull
Чем отличаются эти 3 аннотации? Все ли они нужны:
 @NotBlank
    @NotEmpty
    @NotNull

2022-08-10 20:29 UTC, OlgaSergeenko commented on .gitignore
> -target/
Я добавила все обратно в gitignore. Правда все равно пока вижу, что написано, changed files - 106.... или это не там надо смотреть?

2022-08-10 20:30 UTC, OlgaSergeenko commented on pom.xml
> +			<version>1.18.20</version>
Добавила

2022-08-10 20:30 UTC, OlgaSergeenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!films.containsKey(film.getId())) {
Да, перенесла его, спасибо!

2022-08-10 20:32 UTC, OlgaSergeenko commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(String name, String description, LocalDate releaseDate, int duration) {
Получается, только для Film это подходит. У User поле name может быть пустым по условию, значит ему не добавить @NonNull, а без нее как я поняла не заработает RequaredArgsContructor

2022-08-11 07:35 UTC, Frilock commented on .gitignore
> -target/
Да, там, я тоже вижу 106 файлов и это конечно не очень хорошо. Я вот что думаю, у Вас есть возможность удалить этот Пул реквест и создать новый? Попробуйте первым коммитом добавить только gitignore файл.
То есть когда вы коммит делаете вы не все файлы добавляйте, а только его. Если у Вас сроки не горят, я бы посоветовал поразбираться с git поскольку это важный инструмент и он точно будет использоваться на работе.

2022-08-11 07:40 UTC, closed without merging

2022-08-11 07:43 UTC, Frilock reviewed
Предлагаю немного с git поразбираться если есть время у Вас, этот навык точно пригодится в работе, потом я приму работу, если не получится попробуйте задать вопрос коллегам/наставнику или если не ответят то напишите

2022-08-11 07:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final static Logger log = LoggerFactory.getLogger(FilmController.class);
Можете воспользоваться аннотацией на контроллер Slf4j от ломбока.

2022-08-11 07:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +
Пустая строка