ТЗ 10
OlgaSergeenko/java-filmorate pull request #3
Opened 2022-08-21 18:39 UTC by OlgaSergeenko

2022-08-21 19:38 UTC, Frilock requested changes
Добрый вечер, написал пару комментариев к коду. Жду новую иттерацию

2022-08-21 19:38 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(
Вроде в одну строчку влезает, зачем переносы делать?

2022-08-21 19:38 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Constants.java
> +    public final static Logger LOG_FILM_CONTROLLER = LoggerFactory.getLogger(FilmController.class);
Вот так делать не нужно, именно логер переносить не принято. Я вроде Вам писал, что вы над классом можете просто аннотацию slf4j повесить и использовать log. и т.д.

2022-08-21 19:38 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +public class ErrorResponse {
А зачем Вам данный класс? почему просто строкой не воспользоваться? зачем обертку делать?

2022-08-21 19:38 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Set<Long> likes = new HashSet<>();
Модификатор забыли. Для билдера можете повесить на поле Builder.defualt

2022-08-21 19:38 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    InMemoryFilmStorage inMemoryFilmStorage;
Модификаторы?

2022-08-21 19:38 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    InMemoryUserStorage inMemoryUserStorage;
Помните я Вам в 3-5 работе писал комментарий о том, что в сигнатуре метода нужно указывать интерфейс, а не реализацию. Вот тут тоже самое. У Вас есть интерфейс FilmStorage. Сейчас у него одна реализация, но на деле их может быть несколько, поэтому правильнее писать FilmStorage inMemoryFilmStorage

2022-08-21 19:38 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(InMemoryFilmStorage inMemoryFilmStorage, InMemoryUserStorage inMemoryUserStorage) {
Тут аналогично.  Потом в дальнейшем если реализаций много, нужно использовать аннотацию Qualifaer

2022-08-21 19:38 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    @Override
отстутипе строчку

2022-08-21 19:38 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Set<Long> removeLike(long filmId, long userId) {
Кроме того, не вижу тестового покрытия для новых методов.

2022-08-23 08:06 UTC, OlgaSergeenko commented
Насчет класса ErrorResponse. Нам говорили в теории, что частая практика — создание специального объекта для универсального формата ошибки. 
Но что-то я теперь сама не оч понимаю, зачем он, поэтому я удалила и сделала строкой, как вы написали.

2022-08-23 16:14 UTC, Frilock requested changes
Добрый день, написал пару комментариев к работе.

2022-08-23 16:14 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectParameterException.java
> +public class IncorrectParameterException extends RuntimeException {
Что то мне не нравится этот класс. Во первых, между методом и конструктором нужно строчку пропустить, во вторых, лишний пропуск строки в конструкторе, в третьих, а зачем такой класс нужен? Вот вы передали сюда параметр, например, count, а дальше что? Не нужно ли было в данном классе в конструкторе по аналогии с другими классами super вызывать? Или у вас специально идея такая была?
Это скорее вопрос на обсуждение.

2022-08-23 16:14 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmStorage inMemoryFilmStorage, UserStorage inMemoryUserStorage) {
Кстати ломбок позволяет отказаться от такого конструктора, используя аннотацию RequaredArgsConstructor. Это так, вдруг не знали

2022-08-23 16:14 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +public interface FilmStorage extends AbstractController<Film> {
А зачем FilmStorage наследуется от Абстрактного контроллера? Этот момент не понял
Вы тогда похожий интерфейс для Storage создать должны и его использовать

2022-08-23 16:14 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    @Override
Нужно пропустить строчку

2022-08-23 16:14 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +public interface UserStorage extends AbstractController<User> {
Аналогично

2022-08-23 16:14 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Constants.java
> +package ru.yandex.practicum.filmorate.model;
Предлагаю создать пакет util  и туда перенести этот класс

2022-08-24 21:09 UTC, OlgaSergeenko commented
Идея с ParameterException заключалась в том, чтобы сообщать о том, с каким параметром допущена ошибка, но я забыла добавить строку с текстом, добавила.
Я немного запуталась, кто от кого должен зависеть, кто чей интерфейс и кто что кому передает. Посмотрите пожалуйста в новой версии, верно ли?

2022-08-25 05:57 UTC, Frilock approved these changes
Принято

2022-08-25 05:57 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectParameterException.java
> +    public IncorrectParameterException(String parameter) {
Странно, комментарий по данному классу писал, а он пропал. Не очень мне нравиться данное исключение, плюс тут у Вас все сьехало.

2022-08-25 11:15 UTC, merged