Add database
OlgaSergeenko/java-filmorate pull request #6
Opened 2022-09-26 21:01 UTC by OlgaSergeenko

2022-09-27 16:21 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе. Жду новую итерацию

2022-09-27 16:21 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        System.out.println(Arrays.toString(e.getStackTrace()));
А это зачем?

2022-09-27 16:21 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@Component
Аннотация Component не нужна, у вас уже висит RestController

2022-09-27 16:21 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    private int id;
Не критично, но в качестве идентификатора лучше long использовать, вроде писал Вам об этом уже

2022-09-27 16:21 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    public Mpa(int id, String name) {
Раз вы lombok используете то давайте тогда заменим на AllArgsConstructor

2022-09-27 16:21 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(@Qualifier ("filmDbStorage")FilmStorage filmStorage,
Тут форматирование съехало. После Qualifier пробел не не нужен, а перед FilmStorage наоборот нужен

2022-09-27 16:21 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    filmsRows.getDate("release_date").toLocalDate(),
У вас тут всегда значение возвращается? filmsRows.getDate("release_date"). Вы тут NPE не получите?

2022-09-27 16:21 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            log.info("Фильм с идентификатором {} не найден.", id);
Вы бросаете исключение, а в log пишите с уровнем info. Это как минимум не логично, пишите так же с уровнем error

2022-09-27 16:21 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    filmsRows.getLong("movie_id"),
Вообще такой маппинг бы в отдельный класс вынести или как минимум метод

2022-09-27 16:21 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            log.debug("Релиз фильма ранее 28/12/1895");
Такой же комментарий про уровни логирования. Проверьте другие места

2022-09-27 16:21 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Optional<Film> getById(long filmId) {
А у Вас сейчас используются эти классы? Если нет то лучше их удалить (тогда Вам квалифаер не понадобится)

2022-09-27 17:19 UTC, OlgaSergeenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        System.out.println(Arrays.toString(e.getStackTrace()));
У меня постоянно вылетала эта ошибка, а я не могла понять, в чем дело. 
Сейчас уже не нужно, удаляю.

2022-09-27 17:22 UTC, OlgaSergeenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    filmsRows.getDate("release_date").toLocalDate(),
У этого поля есть аннотация @NonNull, то есть я так понимаю, пустого значения быть не может.

2022-09-27 17:28 UTC, OlgaSergeenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Optional<Film> getById(long filmId) {
Нет, больше не используется, понятно

2022-09-28 07:46 UTC, OlgaSergeenko commented
"У вас тут всегда значение возвращается? filmsRows.getDate("release_date"). Вы тут NPE не получите?" - У этой колонки в таблицу есть ограничение release_date DATE NOT NULL, то есть я так понимаю, пустого значения быть не может.

В остальном - внесла правки.

2022-09-28 17:22 UTC, Frilock approved these changes
Принято

2022-09-29 18:59 UTC, merged